# NumPy

In [6]:
# - Numpy stands for numerical Python.
# - It is a Python library that is used to perform advanced mathematical computations on the large datsets.
# - Using Numpy we can perform statistical, linear algebric, trignometric operations on the large datasets.
# - Using Numpy we can simualate random data
# - To use Numpy we have to import it first.

# Importing Numpy

In [10]:
import numpy as np

In [12]:
print(dir())

['In', 'Out', '_', '_1', '_11', '_3', '_5', '_7', '_8', '_9', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__pandas', '__spec__', '_dh', '_i', '_i1', '_i10', '_i11', '_i12', '_i2', '_i3', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', 'dataframe_columns', 'dataframe_hash', 'dtypes_str', 'exit', 'get_dataframes', 'get_ipython', 'getpass', 'hashlib', 'import_pandas_safely', 'is_data_frame', 'json', 'np', 'open', 'quit']


# Version

In [15]:
np.__version__

'1.24.3'

# Version of Python

In [1]:
!pip -V

zsh:1: command not found: pip


In [24]:
import sys

In [26]:
sys.version

'3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)]'

In [32]:
# - Numpy works with a special data structure known as array.

# Array

In [39]:
# - It is a collection of homogenous (same type) elements.
# - Array is a data structure provided by Numpy.
# - Using arrays we can perform operations on the large data with less lines of code.
# - Arrays are faster compared to list so they become very useful with the large data.

# How to create an array?

In [44]:
# np.array(value/iterable)- It returns an array object

In [46]:
x=np.array(45)
x

array(45)

In [48]:
print(x,type(x))

45 <class 'numpy.ndarray'>


In [50]:
x=np.array(True)
x

array(True)

In [54]:
x=np.array([10,20,30,40,50])
x

array([10, 20, 30, 40, 50])

In [56]:
print(x)

[10 20 30 40 50]


In [58]:
print([10,20,30,40,50])

[10, 20, 30, 40, 50]


In [60]:
x=np.array((10,20,30,40,50))
x

array([10, 20, 30, 40, 50])

In [64]:
x=np.array({1:100,2:200})
x

array({1: 100, 2: 200}, dtype=object)

In [68]:
x=np.array({1,2,3,4,5})
x

array({1, 2, 3, 4, 5}, dtype=object)

# List vs Arrays

In [71]:
# - Arrays need less code to perform operations.
# - Arrays are faster than list.

In [79]:
lst=[1,2,3,4,5,6,7,8,9,10]
# Multiply each element of the above list by 5
res=[]
for i in lst:
    res.append(i*5)
print(res)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [81]:
lst=[1,2,3,4,5,6,7,8,9,10]
# Multiply each element of the above list by 5

for i in range(len(lst)):
    lst[i]=lst[i]*5
print(lst)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [93]:
lst=[1,2,3,4]
lst*5 # Repeatition

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [87]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
x*5 # Multiplication

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [89]:
x**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [91]:
x/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [101]:
x%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [109]:
import time

In [111]:
st=time.time()
lst=[i for i in range(1000000)]
for i in range(len(lst)):
    lst[i]=lst[i]*5
print(lst[0],lst[-1])
tt=time.time()-st
print(tt)

0 4999995
0.1506025791168213


In [113]:
st=time.time()
x=np.arange(1000000)
x*5
tt=time.time()-st
print(tt)

0.0030035972595214844


In [115]:
# - List is a collection of heterogenous elements.
# - Array is the collection of homogenous elements.

In [117]:
x=np.array([10,20,30,40,50])
x

array([10, 20, 30, 40, 50])

In [119]:
lst=[True, 'Python', 5+5j, {1:100,2:200}, 2.8888]

# Array Upcasting

In [124]:
# int -> float -> complex -> string -> object

In [130]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [132]:
x.dtype

dtype('int32')

In [134]:
x=np.array([1,2,3.6,4,5])
x

array([1. , 2. , 3.6, 4. , 5. ])

In [136]:
x.dtype

dtype('float64')

In [138]:
x=np.array([1,2,3.6,4+4j,5])
x

array([1. +0.j, 2. +0.j, 3.6+0.j, 4. +4.j, 5. +0.j])

In [140]:
x.dtype

dtype('complex128')

In [142]:
x=np.array([1,2,3+6j,4,5])
x

array([1.+0.j, 2.+0.j, 3.+6.j, 4.+0.j, 5.+0.j])

In [144]:
x=np.array([1,2+5j,3.6,'4',5])
x

array(['1', '(2+5j)', '3.6', '4', '5'], dtype='<U64')

In [150]:
x=np.array([1,[2,3.6],4,5],dtype=object)
x

array([1, list([2, 3.6]), 4, 5], dtype=object)

In [154]:
x=np.array([1,2,3,4,5, True])
x

array([1, 2, 3, 4, 5, 1])

In [156]:
x=np.array([1,False,2,3.6,4,5])
x

array([1. , 0. , 2. , 3.6, 4. , 5. ])

In [158]:
x=np.array([1,2,3.6,4,5, None])
x

array([1, 2, 3.6, 4, 5, None], dtype=object)

# Attributes on arrays

In [161]:
# shape
# size
# dtype
# ndim

### dtype

In [164]:
# - It returns the type of the elements the array contains.

In [166]:
x=np.array([1,False,2,3.6,4,5])
x

array([1. , 0. , 2. , 3.6, 4. , 5. ])

In [168]:
x.dtype

dtype('float64')

### size

In [171]:
# - It returns the number of elements in an array.

In [173]:
x=np.array([10,20,30,40,50,60,70,80])
x

array([10, 20, 30, 40, 50, 60, 70, 80])

In [175]:
x.size

8

In [177]:
len(x)

8

### shape

In [188]:
# - It returns a tuple that represents the shape of the array.
# (int,) -> Number of elements in the array
# (int,int) -> Number of rows and the number of columns in the array.

In [182]:
x=np.array([10,20,30,40,50,60,70,80])
x

array([10, 20, 30, 40, 50, 60, 70, 80])

In [186]:
x.shape

(8,)

In [192]:
x=np.array([[10,20],[30,40],[50,60],[70,80]])
x

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [196]:
x.shape

(4, 2)

### ndim

In [199]:
# - It returns the dimension of the array.

In [205]:
x=np.array([10,20,30,40,50,60,70,80])
x

array([10, 20, 30, 40, 50, 60, 70, 80])

In [207]:
x.ndim

1

In [209]:
x=np.array([[10,20],[30,40],[50,60],[70,80]])
x

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [211]:
x.ndim

2

In [213]:
x.size

8

# Creating different kind of arrays

### np.arange()

In [220]:
# - It creates an array of numbers within a given range.

In [222]:
# np.arange(start,stop,step)
# stop value is exluded

In [224]:
# Create an array of number from 1 to 10

In [228]:
lst=[i for i in range(1,11)]
x=np.array(lst)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [232]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [234]:
# Create an array of even numbers from 2 to 20.

In [238]:
x=np.arange(2,21,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [240]:
# [1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8]

In [258]:
x=np.arange(1,8.1,.5)
x

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. ])

### np.linspace()

In [261]:
# - It creates an array of the equally spaced values.

In [265]:
# np.linspace(start,stop, the number of values)
# start and stop both are included.

In [267]:
# Create an array of equally spaced 5 numbers between 1 and 10.
# Create a an array of 5 numbers from 1 to 10.
# The difference between any two consecutive numbers has to be the same.

In [269]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [271]:
3.25-1

2.25

In [275]:
5.5-3.25

2.25

In [277]:
7.75-5.5

2.25

In [279]:
10-7.75

2.25

In [293]:
np.linspace(1,10,5000)

array([ 1.        ,  1.00180036,  1.00360072, ...,  9.99639928,
        9.99819964, 10.        ])

In [303]:
# Arithmetic Progression
# l=a+(n-1)d
# l- last element
# a- first element
# d- common difference (step size)
# n- The number of values

In [297]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [305]:
a=1
l=10
n=5
# d=?

In [309]:
# 10=1+(5-1)d
# 10=1+4d
# 4d=9
d=9/4
d

2.25

In [311]:
np.linspace(1,100,15)

array([  1.        ,   8.07142857,  15.14285714,  22.21428571,
        29.28571429,  36.35714286,  43.42857143,  50.5       ,
        57.57142857,  64.64285714,  71.71428571,  78.78571429,
        85.85714286,  92.92857143, 100.        ])

In [315]:
d=(100-1)/(15-1)
d

7.071428571428571

### en.eye()

In [320]:
# - It is used to create an identity matrix.
# - An identity matrix is a square matrix in which the diagonals are 1's and the rest are 0's
# - Though an identity matrix is a square matrix but in numpy we can create of any shape

In [322]:
# np.eye(rows,cols)

In [324]:
# Create a 3*3 identity matrix

In [328]:
x=np.eye(3,3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [330]:
x.dtype

dtype('float64')

In [332]:
x=np.eye(3,3,dtype=int)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [334]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [349]:
np.eye(3,5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

### np.zeros()

In [339]:
# - It creates an array of 0's

In [351]:
# np.zeros((rows,cols),dtype=)

In [353]:
# Create a 3*3 array of 0's

In [357]:
x=np.zeros((3,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [359]:
x.dtype

dtype('float64')

In [363]:
x=np.zeros((3,3),dtype=int)
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [365]:
x.dtype

dtype('int32')

## np.ones()

In [368]:
# - It creates an array of 1's

In [370]:
# np.ones((rows,cols),dtype=)

In [372]:
# Create a 4*4 array of 1's

In [376]:
x=np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [378]:
x.dtype

dtype('float64')

In [380]:
x=np.ones((4,4),dtype=int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [382]:
x.dtype

dtype('int32')

In [386]:
x=np.ones((3,7),dtype=int)
x

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [388]:
# Create a 3*4 array that has all the values to be 2.5

In [394]:
x=np.ones((3,4))*2.5
x

array([[2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5]])

In [400]:
x=np.zeros((3,4))+2.5
x

array([[2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5]])

### np.full()

In [403]:
# - It creates an array of the given shape and the given value.

In [405]:
# np.full((rows,cols),value)

In [407]:
# Create a 3*4 array that has all the values to be 2.5

In [411]:
x=np.full((3,4),2.5)
x

array([[2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5]])

In [427]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

### np.zeros_like()

In [430]:
# - It takes an array as an argument.
# - It creates an array of 0's of the shape of the given array.

In [434]:
x=np.array([[5,7,9],[8,8,4]])
x

array([[5, 7, 9],
       [8, 8, 4]])

In [436]:
x.shape

(2, 3)

In [438]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [446]:
x=np.array([[1,2],[8,9],[7,7],[4,2]])
x

array([[1, 2],
       [8, 9],
       [7, 7],
       [4, 2]])

In [448]:
x.shape

(4, 2)

In [450]:
np.zeros_like(x)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

### np.ones_like()

In [453]:
# - It takes an array as an argument.
# - It creates the array of 1's of the shape of the given array.

In [455]:
# np.ones_like(arr)

In [457]:
x

array([[1, 2],
       [8, 9],
       [7, 7],
       [4, 2]])

In [459]:
x.shape

(4, 2)

In [461]:
np.ones_like(x)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [463]:
x=np.array([[5,7,9],[8,8,4]])
x

array([[5, 7, 9],
       [8, 8, 4]])

In [465]:
x.shape

(2, 3)

In [467]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

### np.full_like()

In [470]:
# - It takes an array and a value as arguments.
# - It creates an array of the given value and of the shape of the given array.

In [472]:
# np.full_like(arr,value)

In [474]:
x

array([[5, 7, 9],
       [8, 8, 4]])

In [476]:
np.full_like(x,24)

array([[24, 24, 24],
       [24, 24, 24]])

In [478]:
np.full_like(x,4.8)

array([[4, 4, 4],
       [4, 4, 4]])

In [480]:
np.full_like(x,4.8,dtype=float)

array([[4.8, 4.8, 4.8],
       [4.8, 4.8, 4.8]])

In [482]:
x

array([[5, 7, 9],
       [8, 8, 4]])

In [484]:
x.dtype

dtype('int32')

In [490]:
np.full_like(x,'a',dtype=str)

array([['a', 'a', 'a'],
       ['a', 'a', 'a']], dtype='<U1')

In [492]:
# int('a')

### np.diag()

In [497]:
# - It creates a diagonal array.
# - In a diagonal array all the non-diagonal elements are 0's.

In [501]:
# np.diagonal([diagonal_elements])

In [503]:
lst=[5,10,15,20]

In [518]:
x=np.diag(lst)
x

array([[ 5,  0,  0,  0],
       [ 0, 10,  0,  0],
       [ 0,  0, 15,  0],
       [ 0,  0,  0, 20]])

In [520]:
x.shape

(4, 4)

In [514]:
x=np.diag(np.array([4,6,8,7,2]))
x

array([[4, 0, 0, 0, 0],
       [0, 6, 0, 0, 0],
       [0, 0, 8, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 2]])

In [516]:
x.shape

(5, 5)

In [565]:
np.diag([1,2,3,4],k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [567]:
np.diag([1,2,3,4],k=-2)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0]])

### np.diagonal()

In [523]:
# - It returns the main diagonal from an array.

In [527]:
x=np.random.randint(10,100,size=(5,5))

In [529]:
x

array([[29, 23, 41, 45, 36],
       [53, 24, 92, 76, 19],
       [96, 71, 33, 39, 60],
       [31, 56, 79, 68, 66],
       [24, 45, 93, 35, 66]])

In [531]:
np.diagonal(x)

array([29, 24, 33, 68, 66])

In [533]:
np.diagonal(x,offset=1)

array([23, 92, 39, 66])

In [535]:
np.diagonal(x,offset=2)

array([41, 76, 60])

In [537]:
np.diagonal(x,offset=3)

array([45, 19])

In [539]:
np.diagonal(x,offset=4)

array([36])

In [541]:
np.diagonal(x,offset=5)

array([], dtype=int32)

In [543]:
np.diagonal(x,offset=-1)

array([53, 71, 79, 35])

In [545]:
np.diagonal(x,offset=-2)

array([96, 56, 93])

In [547]:
np.diagonal(x,offset=-3)

array([31, 45])

In [549]:
np.diagonal(x,offset=-4)

array([24])

In [551]:
np.diagonal(x,offset=-5)

array([], dtype=int32)

In [553]:
x=np.random.randint(10,100,size=(3,5))

In [555]:
x

array([[75, 91, 13, 90, 71],
       [32, 68, 79, 17, 73],
       [92, 18, 80, 80, 17]])

In [557]:
np.diagonal(x)

array([75, 68, 80])

In [559]:
np.diagonal(x,offset=1)

array([91, 79, 80])

### np.trace()

In [570]:
# - It returns the sum of the diagonal of an array.

In [572]:
x=np.random.randint(10,100,size=(5,5))

In [574]:
x

array([[23, 97, 21, 28, 61],
       [26, 80, 75, 69, 68],
       [81, 59, 48, 16, 80],
       [32, 50, 69, 63, 69],
       [34, 25, 69, 15, 93]])

In [576]:
np.trace(x)

307

In [580]:
np.diagonal(x).sum()

307

In [582]:
np.trace(x,offset=1)

257

In [586]:
np.diagonal(x,offset=1).sum()

257

In [588]:
np.trace(x,offset=-1)

169

In [592]:
np.diagonal(x,offset=-1).sum()

169

# Creating 0-D

In [595]:
# 0-D- The array with no dimension

In [597]:
# np.array(element)

In [601]:
x=np.array(1500)
x

array(1500)

In [603]:
x.shape

()

In [605]:
x.ndim

0

# Creating 1-D arrays

In [609]:
# - A 1-D array can be created using a single list or tuple.

In [613]:
lst=[10,20,30,40,50,60,70,80]
x=np.array(lst)
x

array([10, 20, 30, 40, 50, 60, 70, 80])

In [617]:
x.shape

(8,)

In [619]:
x.ndim

1

In [621]:
lst=(10,20,30,40,50,60,70,80)
x=np.array(lst)
x

array([10, 20, 30, 40, 50, 60, 70, 80])

In [623]:
x.ndim

1

In [625]:
x.shape

(8,)

# Creating a 2-D array