In [44]:
# Conditions on arrays 
# Iterating over arrays
# Array concatenation
# Sorting of arrays
# Splitting of arrays
# Array broadcasting
# (h_stact, v_stack)

In [3]:
import numpy as np

# Concatenation of arrays

In [6]:
# np.concatenate((arr_1m,arr_2),axis=0/1)

In [8]:
# vertical concatenation
# - The number of columns have to be equal.
# - axis=0

In [12]:
# Horizontal concatenation
# - The number of rows have to be equal.
# - axis=1

In [14]:
x=np.array([[10,20,30],[4,5,6]])
x

array([[10, 20, 30],
       [ 4,  5,  6]])

In [16]:
y=np.array([[2,4,6]])
y

array([[2, 4, 6]])

In [18]:
np.concatenate((x,y),axis=0)

array([[10, 20, 30],
       [ 4,  5,  6],
       [ 2,  4,  6]])

In [20]:
np.concatenate((x,y))

array([[10, 20, 30],
       [ 4,  5,  6],
       [ 2,  4,  6]])

In [24]:
# np.concatenate((x,y),axis=1)

In [26]:
z=np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [28]:
x

array([[10, 20, 30],
       [ 4,  5,  6]])

In [34]:
np.concatenate((x,z),axis=1)

array([[10, 20, 30,  1,  2],
       [ 4,  5,  6,  3,  4]])

In [42]:
# np.hstack((arr_1,arr_2)) -> horizontal concatenation
# np.vstack((arr_1,arr_2)) -> vertical concatenation

In [38]:
np.hstack((x,z))

array([[10, 20, 30,  1,  2],
       [ 4,  5,  6,  3,  4]])

In [40]:
np.vstack((x,y))

array([[10, 20, 30],
       [ 4,  5,  6],
       [ 2,  4,  6]])

# Conditions on arrays

In [49]:
np.random.seed(48)
x=np.random.randint(10,100,size=(3,4))

In [51]:
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [59]:
# Get the values>55
x>55

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True, False, False]])

In [61]:
x[x>55]

array([61, 91, 78, 58, 74, 80, 80, 90])

In [67]:
# Get the values<55
x[x<55]

array([10, 44, 39, 16])

In [69]:
np.where(x<55)

(array([0, 2, 2, 2], dtype=int64), array([0, 0, 2, 3], dtype=int64))

In [73]:
x=np.array([[10,0,0],[4,6,0],[0,0,8]])
x

array([[10,  0,  0],
       [ 4,  6,  0],
       [ 0,  0,  8]])

In [77]:
(x==0).sum()

5

In [81]:
x[x!=0]

array([10,  4,  6,  8])

In [85]:
x[x==0]

array([0, 0, 0, 0, 0])

# Iterating over arrays

In [90]:
# - Applying loop on arrays

In [92]:
x=np.array([10,20,30,40,50,60,70,80])
x

array([10, 20, 30, 40, 50, 60, 70, 80])

In [94]:
for i in x:
    print(i)

10
20
30
40
50
60
70
80


In [98]:
x=np.array([10,20,30,40,50,60,70,90,15,25,45,55]).reshape(3,4)
x

array([[10, 20, 30, 40],
       [50, 60, 70, 90],
       [15, 25, 45, 55]])

In [104]:
for i in x:
    print(i)
    # break

[10 20 30 40]
[50 60 70 90]
[15 25 45 55]


In [106]:
i=np.array([10,30,30,40])
for j in i:
    print(j)

10
30
30
40


In [110]:
for i in x:
    for j in i:
        print(j)

10
20
30
40
50
60
70
90
15
25
45
55


In [112]:
x

array([[10, 20, 30, 40],
       [50, 60, 70, 90],
       [15, 25, 45, 55]])

In [114]:
x.ravel()

array([10, 20, 30, 40, 50, 60, 70, 90, 15, 25, 45, 55])

In [116]:
for i in x.ravel():
    print(i)

10
20
30
40
50
60
70
90
15
25
45
55


In [118]:
x

array([[10, 20, 30, 40],
       [50, 60, 70, 90],
       [15, 25, 45, 55]])

In [120]:
x.T

array([[10, 50, 15],
       [20, 60, 25],
       [30, 70, 45],
       [40, 90, 55]])

In [122]:
for i in x.T:
    print(i)

[10 50 15]
[20 60 25]
[30 70 45]
[40 90 55]


In [126]:
x

array([[10, 20, 30, 40],
       [50, 60, 70, 90],
       [15, 25, 45, 55]])

In [124]:
for i in x.T.ravel():
    print(i)

10
50
15
20
60
25
30
70
45
40
90
55


# Sorting an array

### np.sort()

In [140]:
# - It sorts an array in the ascending order and return a new array.

In [131]:
x=np.array([2,8,4,6,9,7,4,6])
x

array([2, 8, 4, 6, 9, 7, 4, 6])

In [142]:
np.sort(x)

array([2, 4, 4, 6, 6, 7, 8, 9])

In [144]:
x

array([2, 8, 4, 6, 9, 7, 4, 6])

In [146]:
x

array([2, 8, 4, 6, 9, 7, 4, 6])

In [150]:
np.sort(x)[::-1]

array([9, 8, 7, 6, 6, 4, 4, 2])

In [152]:
x

array([2, 8, 4, 6, 9, 7, 4, 6])

### arr.sort()

In [156]:
# - It sorts the array in ascending order.
# - It makes the changes in the existing array. It does not return anything.

In [158]:
x

array([2, 8, 4, 6, 9, 7, 4, 6])

In [160]:
x.sort()

In [162]:
x

array([2, 4, 4, 6, 6, 7, 8, 9])

In [166]:
x[::-1]

array([9, 8, 7, 6, 6, 4, 4, 2])

In [168]:
np.random.seed(48)
x=np.random.randint(10,100,size=(3,4))

In [170]:
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [180]:
np.sort(x,axis=1)

array([[10, 61, 78, 91],
       [58, 74, 80, 80],
       [16, 39, 44, 90]])

In [174]:
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [178]:
np.sort(x,axis=0)

array([[10, 61, 39, 16],
       [44, 74, 80, 78],
       [58, 90, 91, 80]])

In [182]:
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [186]:
np.sort(x,axis=0)[::-1]

array([[58, 90, 91, 80],
       [44, 74, 80, 78],
       [10, 61, 39, 16]])

In [188]:
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [190]:
np.sort(x,axis=1)

array([[10, 61, 78, 91],
       [58, 74, 80, 80],
       [16, 39, 44, 90]])

In [192]:
np.sort(x,axis=1)[::,::-1]

array([[91, 78, 61, 10],
       [80, 80, 74, 58],
       [90, 44, 39, 16]])

# Array Broadcasting

In [195]:
# - When we perform some operation with two arrays and their shape is not the same.
# - Then numpy automatically adds the summy rows or dummy columns to match the shape.
# - Once the shape is matched then it performs vectorised operation (index to index) operation.
# - This enables us to perform operations on the arrays of different shape.

In [197]:
# Conditions
# - Either of the dimension has to be the same in both the arrays.
# - The other diemension has to be one in either of the arrays.

In [201]:
x=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [205]:
y=np.array([[10,20,30]])
y

array([[10, 20, 30]])

In [207]:
x.shape

(3, 3)

In [211]:
y.shape

(1, 3)

In [213]:
x+y

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [215]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [217]:
y=np.array([[2],[4],[8]])
y

array([[2],
       [4],
       [8]])

In [219]:
x.shape

(3, 3)

In [221]:
y.shape

(3, 1)

In [223]:
x*y

array([[ 2,  4,  6],
       [16, 20, 24],
       [56, 64, 72]])

In [225]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [229]:
y=np.array([[10,20,30],[4,4,6]])
y

array([[10, 20, 30],
       [ 4,  4,  6]])

In [231]:
x.shape

(3, 3)

In [233]:
y.shape

(2, 3)

In [235]:
x*y

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 