In [1]:
import numpy as np

# Arithmetic and Statictical Functions

### np.max()

In [5]:
# - It returns the maximum value of an array.

In [19]:
# np.max(arr,axis=0/1)
# arr.max(axis=0/1)

In [13]:
np.random.seed(115)
x=np.random.randint(10,100,size=(3,4))

In [15]:
x

array([[28, 42, 16, 26],
       [24, 41, 51, 72],
       [56, 22, 75, 17]])

In [17]:
np.max(x)

75

In [21]:
x.max()

75

In [23]:
np.max(x,axis=0)

array([56, 42, 75, 72])

In [25]:
np.max(x,axis=1)

array([42, 72, 75])

In [29]:
x.max(axis=0)

array([56, 42, 75, 72])

In [33]:
x.max(axis=1)

array([42, 72, 75])

### np.min()

In [36]:
# - It returns the minimum of an array.

In [38]:
# np.min(arr,axis=0/1)
# arr.min(axis=0/1)

In [40]:
x

array([[28, 42, 16, 26],
       [24, 41, 51, 72],
       [56, 22, 75, 17]])

In [42]:
np.min(x)

16

In [44]:
x.min()

16

In [46]:
np.min(x,axis=0)

array([24, 22, 16, 17])

In [48]:
np.min(x,axis=1)

array([16, 24, 17])

In [52]:
x.min(axis=0)

array([24, 22, 16, 17])

In [54]:
x.min(axis=1)

array([16, 24, 17])

### np.mean()

In [57]:
# - It returns the mean (average) of an array.

In [69]:
# np.mean(arr,axis=0/1)
# arr.mean(axis=0/1)

In [59]:
x

array([[28, 42, 16, 26],
       [24, 41, 51, 72],
       [56, 22, 75, 17]])

In [61]:
np.mean(x)

39.166666666666664

In [63]:
# Total_of_values/number_of_values

In [67]:
np.sum(x)/x.size

39.166666666666664

In [71]:
np.mean(x,axis=1)

array([28. , 47. , 42.5])

In [79]:
x[0].sum()/x[0].size,x[1].sum()/x[1].size,x[2].sum()/x[2].size

(28.0, 47.0, 42.5)

In [81]:
np.mean(x,axis=0)

array([36.        , 35.        , 47.33333333, 38.33333333])

In [83]:
x.mean(axis=0)

array([36.        , 35.        , 47.33333333, 38.33333333])

In [85]:
x.mean(axis=1)

array([28. , 47. , 42.5])

### np.median()

In [90]:
# - It returns the median of an array.
# - Median is the middle value or the 50th percentile value.

In [92]:
# vals=[1,5,9,12,15]
# med=9

In [96]:
# vals=[1,5,9,12,15,20]
# (9+12)/2
# med=10.5

In [100]:
# np.median(arr,axis=0/1)
# arr.median() is not possible

In [102]:
x

array([[28, 42, 16, 26],
       [24, 41, 51, 72],
       [56, 22, 75, 17]])

In [104]:
np.median(x)

34.5

In [108]:
# x.median() -> AttributeError

In [112]:
# data=[24,28,56]
# mean=(28+24+56)/3
# mean -> 36
# median -> 28

In [116]:
np.median(x,axis=0)

array([28., 41., 51., 26.])

In [118]:
np.median(x,axis=1)

array([27., 46., 39.])

In [120]:
data=[28, 42, 16, 26]
ascending=[16,26,28,42]
med=(26+28)/2
med

27.0

### mode()

In [123]:
# - mode() is not available in Numpy.
# - To calculate mode we can use Scipy.
# - Scipy stands for Scientific Python.
# - It is a sister of Numpy

In [125]:
from scipy import stats

In [129]:
# stats.mode(arr,axis=0/1,keepdims=True/False)

In [131]:
x

array([[28, 42, 16, 26],
       [24, 41, 51, 72],
       [56, 22, 75, 17]])

In [135]:
stats.mode(x,keepdims=False)

ModeResult(mode=array([24, 22, 16, 17]), count=array([1, 1, 1, 1]))

In [139]:
arr=np.array([10,20,30,40,20,20,50,20,10,10,20,20]).reshape(3,4)
arr

array([[10, 20, 30, 40],
       [20, 20, 50, 20],
       [10, 10, 20, 20]])

In [155]:
stats.mode(arr,keepdims=False,axis=0)

ModeResult(mode=array([10, 20, 20, 20]), count=array([2, 2, 1, 2]))

In [157]:
stats.mode(arr,keepdims=False,axis=1)

ModeResult(mode=array([10, 20, 10]), count=array([1, 3, 2]))

### np.var()

In [161]:
# - It returns the variance of an array.

In [169]:
# np.var(arr,axis=0/1)
# arr.var(axis=0/1)

In [163]:
x

array([[28, 42, 16, 26],
       [24, 41, 51, 72],
       [56, 22, 75, 17]])

In [167]:
np.var(x)

387.3055555555556

In [171]:
x.var()

387.3055555555556

In [175]:
np.sum(((x-x.mean())**2))/x.size

387.3055555555556

In [178]:
np.var(x,axis=0)

array([202.66666667,  84.66666667, 586.88888889, 580.22222222])

In [180]:
np.var(x,axis=1)

array([ 86.  , 301.5 , 577.25])

In [182]:
x.var()

387.3055555555556

In [184]:
x.var(axis=0)

array([202.66666667,  84.66666667, 586.88888889, 580.22222222])

In [186]:
x.var(axis=1)

array([ 86.  , 301.5 , 577.25])

### np.std()

In [190]:
# - It returns Standard deviation of an array.
# - Standard deviation is the square root of variance.

In [198]:
# np.std(arr,axis=0/1)
# arr.std(axis=0/1)

In [192]:
x

array([[28, 42, 16, 26],
       [24, 41, 51, 72],
       [56, 22, 75, 17]])

In [194]:
np.std(x)

19.68008017147175

In [196]:
x.std()

19.68008017147175

In [202]:
np.sqrt(x.var())

19.68008017147175

In [208]:
np.sqrt(np.sum((x-x.mean())**2)/x.size)

19.68008017147175

In [210]:
np.std(x,axis=0)

array([14.23610434,  9.20144916, 24.22578975, 24.08780235])

In [212]:
np.std(x,axis=1)

array([ 9.2736185 , 17.36375535, 24.02602755])

In [214]:
x.std(axis=0)

array([14.23610434,  9.20144916, 24.22578975, 24.08780235])

In [216]:
x.std(axis=1)

array([ 9.2736185 , 17.36375535, 24.02602755])

### np.percentile()

In [219]:
# - It returns the specified percentile value from an array.

In [224]:
# np.percentile(arr,percentile_value)

In [226]:
x

array([[28, 42, 16, 26],
       [24, 41, 51, 72],
       [56, 22, 75, 17]])

In [228]:
np.percentile(x,25)

23.5

In [230]:
np.percentile(x,50)

34.5

In [232]:
np.median(x)

34.5

In [234]:
np.percentile(x,75)

52.25

In [236]:
np.percentile(x,[10,25,50,75,95,99])

array([17.5 , 23.5 , 34.5 , 52.25, 73.35, 74.67])

### Transpose of an array

In [239]:
# - Converting the rows into columns and vide versa is known as the transpose of an array.

In [245]:
# arr.T
# - It retsuns a new array.

In [241]:
x

array([[28, 42, 16, 26],
       [24, 41, 51, 72],
       [56, 22, 75, 17]])

In [247]:
x.T

array([[28, 24, 56],
       [42, 41, 22],
       [16, 51, 75],
       [26, 72, 17]])

In [249]:
x

array([[28, 42, 16, 26],
       [24, 41, 51, 72],
       [56, 22, 75, 17]])

### Determinant of a matrix

In [252]:
# - Determinant can be calculated of the square matrix only.
# - Square matrix- rows=cols

In [258]:
# np.linalg.det(arr)

In [254]:
np.random.seed(55)
arr=np.random.randint(10,100,size=(3,3))

In [256]:
arr

array([[87, 36, 49],
       [82, 39, 71],
       [65, 47, 43]])

In [260]:
np.linalg.det(arr)

-40585.00000000003

### Inverse of an array

In [263]:
# - Inverse can be calculated of the square matrix only.
# - Square matrix- rows=cols

In [265]:
# np.linalg.inv(arr)

In [269]:
arr

array([[87, 36, 49],
       [82, 39, 71],
       [65, 47, 43]])

In [271]:
np.linalg.inv(arr)

array([[ 0.04090181, -0.01860293, -0.01589257],
       [-0.02683257, -0.01369964,  0.05319699],
       [-0.03249969,  0.04309474, -0.01086608]])

### Dot product of two arrays

In [276]:
# - The number of columns in the first array should be equal to the number of rows in the second array.

In [274]:
# arr_1.dot(arr_2)

In [278]:
A=np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [280]:
B=np.array([[2],[4],[6]])
B

array([[2],
       [4],
       [6]])

In [282]:
A.shape

(2, 3)

In [284]:
B.shape

(3, 1)

In [286]:
A.dot(B)

array([[28],
       [64]])

In [288]:
B.shape

(3, 1)

In [290]:
A.shape

(2, 3)

In [294]:
B.dot(A)

ValueError: shapes (3,1) and (2,3) not aligned: 1 (dim 1) != 2 (dim 0)

In [296]:
A=np.array([[1,2],[2,-2]])
A

array([[ 1,  2],
       [ 2, -2]])

In [298]:
B=np.array([[10],[35]])
B

array([[10],
       [35]])

In [304]:
x,y=np.linalg.inv(A).dot(B)

In [306]:
x

array([15.])

In [308]:
y

array([-2.5])

### np.argmin()

In [311]:
# - It returns the index of the minimum number.
# - In case of two minimums it returns the index of the first minimum.
# - If an aray is a 2-D or 3-D array then it first converts that into 1-D array and then checks the index.

In [315]:
x=np.array([7,4,9,2,11,6,14,3,8])
x

array([ 7,  4,  9,  2, 11,  6, 14,  3,  8])

In [317]:
np.argmin(x)

3

In [319]:
x[np.argmin(x)]

2

In [321]:
x=np.array([7,4,9,2,11,6,2,14,3,8])
x

array([ 7,  4,  9,  2, 11,  6,  2, 14,  3,  8])

In [323]:
np.argmin(x)

3

In [325]:
x=np.array([[5,9,14],[3,17,4],[1,8,9]])
x

array([[ 5,  9, 14],
       [ 3, 17,  4],
       [ 1,  8,  9]])

In [327]:
np.argmin(x)

6

In [329]:
x.ravel()

array([ 5,  9, 14,  3, 17,  4,  1,  8,  9])

In [331]:
x=np.array([[5,9,14],[3,1,4],[1,8,9]])
x

array([[ 5,  9, 14],
       [ 3,  1,  4],
       [ 1,  8,  9]])

In [333]:
np.argmin(x)

4

In [335]:
x.ravel()

array([ 5,  9, 14,  3,  1,  4,  1,  8,  9])

### np.argmax()

In [338]:
# - It returns the index of the maximum number.
# - In case of two maximums it returns the index of the first maximum.
# - If an aray is a 2-D or 3-D array then it first converts that into 1-D array and then checks the index.

In [342]:
x=np.array([7,4,9,2,11,6,2,14,3,8])
x

array([ 7,  4,  9,  2, 11,  6,  2, 14,  3,  8])

In [344]:
np.argmax(x)

7

In [348]:
x=np.array([7,4,9,14,11,6,2,14,3,8])
x

array([ 7,  4,  9, 14, 11,  6,  2, 14,  3,  8])

In [350]:
np.argmax(x)

3

In [352]:
x=np.array([[5,9,14],[3,17,4],[1,8,9]])
x

array([[ 5,  9, 14],
       [ 3, 17,  4],
       [ 1,  8,  9]])

In [354]:
np.argmax(x)

4

In [356]:
x.ravel()

array([ 5,  9, 14,  3, 17,  4,  1,  8,  9])

### np.argwhere()

In [385]:
# - It returns the index of the non-zero elements.
# - It returns a 2-D array.
# - In case of 1-D array the columns would be 1 (representing indexes of non-zero elements)
# - In case of 2-D array the columns would be 2 (First column row indexes, second column column indexes of non-zero elements)

In [387]:
x=np.array([7,4,0,2,0,6,2,0,0,8])
x

array([7, 4, 0, 2, 0, 6, 2, 0, 0, 8])

In [390]:
np.argwhere(x)

array([[0],
       [1],
       [3],
       [5],
       [6],
       [9]], dtype=int64)

In [392]:
x=np.array([[5,9,0],[0,17,0],[1,0,9]])
x

array([[ 5,  9,  0],
       [ 0, 17,  0],
       [ 1,  0,  9]])

In [394]:
np.argwhere(x)

array([[0, 0],
       [0, 1],
       [1, 1],
       [2, 0],
       [2, 2]], dtype=int64)

# np.where()

### Case_1
- np.where(condition)

In [403]:
# - It returns the indexes of the values where the condition is True.
# - In case of a 1-D array it returns a tuple of single array that contains the indexes.
# - In case of a 2-D array it returns a tuple of two arrays 
# - The first array contains the row indexes and the second array contains the columns indexes.

In [417]:
np.random.seed(55)
x=np.random.randint(10,100,15)
x

array([87, 36, 49, 82, 39, 71, 65, 47, 43, 64, 45, 56, 71, 87, 22])

In [419]:
np.where(x>80)

(array([ 0,  3, 13], dtype=int64),)

In [421]:
np.where(x%2==0)

(array([ 1,  3,  9, 11, 14], dtype=int64),)

In [423]:
arr=x.reshape(3,5)
arr

array([[87, 36, 49, 82, 39],
       [71, 65, 47, 43, 64],
       [45, 56, 71, 87, 22]])

In [425]:
np.where(arr<50)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 4, 2, 3, 0, 4], dtype=int64))

In [435]:
arr[np.where(arr<50)]

array([36, 49, 39, 47, 43, 45, 22])

In [429]:
np.where(arr%2!=0)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 2, 4, 0, 1, 2, 3, 0, 2, 3], dtype=int64))

In [433]:
arr[np.where(arr%2!=0)]

array([87, 49, 39, 71, 65, 47, 43, 45, 71, 87])

### Case_2
- np.where(condition, x, y)

In [439]:
# - If the condition is True then x is the result else y is the result.

In [441]:
x

array([87, 36, 49, 82, 39, 71, 65, 47, 43, 64, 45, 56, 71, 87, 22])

In [443]:
# Convert all the even numbers to 1 and all the odd numbers to 0

In [447]:
np.where(x%2==0,1,0)

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1])

In [451]:
gender=np.array(['male','female','female','male','female','male','male','female'])
gender

array(['male', 'female', 'female', 'male', 'female', 'male', 'male',
       'female'], dtype='<U6')

In [453]:
# male-1
# female-0

In [455]:
np.where(gender=='male',1,0)

array([1, 0, 0, 1, 0, 1, 1, 0])

### Case_3
- np.where(condition, x, arr)

In [458]:
# - Where the condition is True, x is the result else there will not be any change.

In [460]:
x

array([87, 36, 49, 82, 39, 71, 65, 47, 43, 64, 45, 56, 71, 87, 22])

In [462]:
# All the evens should be 1 rest should remain the same.

In [464]:
np.where(x%2==0,1,x)

array([87,  1, 49,  1, 39, 71, 65, 47, 43,  1, 45,  1, 71, 87,  1])

In [466]:
gender

array(['male', 'female', 'female', 'male', 'female', 'male', 'male',
       'female'], dtype='<U6')

In [468]:
# male-1 and female no change

In [470]:
np.where(gender=='male',1,gender)

array(['1', 'female', 'female', '1', 'female', '1', '1', 'female'],
      dtype='<U6')

### Case_4
- capping

In [475]:
data=[1,4,6,8,9,12,18,21,25,32,44,51,56,62,64,75]

# Cap the values in between 8 and 56.
# It means any value that is less than 8 should be 8.
# Any value that is greater than 56 should be 56.

Capped_data=[8,8,8,8,9,12,18,21,25,32,44,51,56,56,56,56]

In [477]:
data=np.array([1,4,6,8,9,12,18,21,25,32,44,51,56,62,64,75])
data

array([ 1,  4,  6,  8,  9, 12, 18, 21, 25, 32, 44, 51, 56, 62, 64, 75])

In [481]:
int=np.where(data<8,8,data)
int

array([ 8,  8,  8,  8,  9, 12, 18, 21, 25, 32, 44, 51, 56, 62, 64, 75])

In [485]:
capped_data=np.where(int>56,56,int)

In [487]:
capped_data

array([ 8,  8,  8,  8,  9, 12, 18, 21, 25, 32, 44, 51, 56, 56, 56, 56])

In [489]:
data

array([ 1,  4,  6,  8,  9, 12, 18, 21, 25, 32, 44, 51, 56, 62, 64, 75])

In [497]:
capped_data=np.where(data<8,8,np.where(data>56,56,data))
capped_data

array([ 8,  8,  8,  8,  9, 12, 18, 21, 25, 32, 44, 51, 56, 56, 56, 56])

# np.clip()

In [500]:
# - It capps the values between two limits.

In [510]:
# np.clip(arr,lower_limit,upper_limit)

In [504]:
data

array([ 1,  4,  6,  8,  9, 12, 18, 21, 25, 32, 44, 51, 56, 62, 64, 75])

In [508]:
np.clip(data,8,56)

array([ 8,  8,  8,  8,  9, 12, 18, 21, 25, 32, 44, 51, 56, 56, 56, 56])

# np.select()

In [517]:
# - It is used when we want to manipulate an array with multiple conditions.

In [519]:
# np.select(cond_list,choice_list,default_value)

In [529]:
mar_status=np.array(['single','unmarried','married','divorced','married','unmarried','widowed','single','divorced'])

In [531]:
mar_status

array(['single', 'unmarried', 'married', 'divorced', 'married',
       'unmarried', 'widowed', 'single', 'divorced'], dtype='<U9')

In [527]:
# single,unmarrued -> unmarried
# married,divorced,widowed -> married

In [541]:
conditions=[mar_status=='single',mar_status=='unmarried',mar_status=='widowed',mar_status=='divorced']
choices=['unmarried','unmarried','married','married']
default_value='married'

In [543]:
np.select(conditions,choices,default_value)

array(['unmarried', 'unmarried', 'married', 'married', 'married',
       'unmarried', 'married', 'unmarried', 'married'], dtype='<U9')

In [549]:
np.where(mar_status=='single','unmarried',
        np.where(mar_status=='divorced','married',
                 np.where(mar_status=='married','married',
                np.where(mar_status=='widowed','married','unmarried'))))

array(['unmarried', 'unmarried', 'married', 'married', 'married',
       'unmarried', 'married', 'unmarried', 'married'], dtype='<U9')

# Missing values in array

In [554]:
# In Numpy the missing values are represented by np.nan
# np.nan is of float type.

In [556]:
type(np.nan)

float

In [558]:
print(np.nan)

nan


In [564]:
arr=np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [566]:
arr.dtype

dtype('int32')

In [568]:
arr=np.array([10,20,np.nan,40])
arr

array([10., 20., nan, 40.])

In [570]:
arr.dtype

dtype('float64')

In [579]:
arr=np.array([10,np.nan,30,40,np.nan,np.nan,70,80,np.nan])
arr

array([10., nan, 30., 40., nan, nan, 70., 80., nan])

In [581]:
arr.dtype

dtype('float64')

### np.isnan()

In [575]:
# - It checkes for np.nan values in an array and returns a boolean array.

In [583]:
arr

array([10., nan, 30., 40., nan, nan, 70., 80., nan])

In [585]:
np.isnan(arr)

array([False,  True, False, False,  True,  True, False, False,  True])

### Count of missing values

In [588]:
arr

array([10., nan, 30., 40., nan, nan, 70., 80., nan])

In [592]:
np.isnan(arr).sum()

4

### Count of non-missing values

In [595]:
arr

array([10., nan, 30., 40., nan, nan, 70., 80., nan])

In [597]:
np.isnan(arr)

array([False,  True, False, False,  True,  True, False, False,  True])

In [605]:
(~np.isnan(arr)).sum()

5

### Extract the missing values

In [608]:
arr

array([10., nan, 30., 40., nan, nan, 70., 80., nan])

In [612]:
np.isnan(arr)

array([False,  True, False, False,  True,  True, False, False,  True])

In [614]:
arr[np.isnan(arr)]

array([nan, nan, nan, nan])

### Extract the non-missing values

In [617]:
arr

array([10., nan, 30., 40., nan, nan, 70., 80., nan])

In [621]:
~np.isnan(arr)

array([ True, False,  True,  True, False, False,  True,  True, False])

In [623]:
arr[~np.isnan(arr)]

array([10., 30., 40., 70., 80.])

In [625]:
arr

array([10., nan, 30., 40., nan, nan, 70., 80., nan])

In [627]:
arr==np.nan

array([False, False, False, False, False, False, False, False, False])

### Indexes of the missing values

In [651]:
arr

array([10., nan, 30., 40., nan, nan, 70., 80., nan])

In [655]:
arr[np.isnan(arr)]

array([nan, nan, nan, nan])

In [659]:
np.where(np.isnan(arr))

(array([1, 4, 5, 8], dtype=int64),)

In [661]:
arr[np.where(np.isnan(arr))]

array([nan, nan, nan, nan])

### Indexes of the non-missing values

In [670]:
arr

array([10., nan, 30., 40., nan, nan, 70., 80., nan])

In [668]:
np.where(~np.isnan(arr))

(array([0, 2, 3, 6, 7], dtype=int64),)

### Replacing the missing values

In [673]:
arr

array([10., nan, 30., 40., nan, nan, 70., 80., nan])

In [679]:
arr[np.isnan(arr)]=0

In [681]:
arr

array([10.,  0., 30., 40.,  0.,  0., 70., 80.,  0.])

# Arrays are mutable

In [684]:
arr

array([10.,  0., 30., 40.,  0.,  0., 70., 80.,  0.])

In [688]:
arr[0]=45

In [690]:
arr

array([45.,  0., 30., 40.,  0.,  0., 70., 80.,  0.])

In [694]:
arr[-1]=500

In [696]:
arr

array([ 45.,   0.,  30.,  40.,   0.,   0.,  70.,  80., 500.])

# Type conversion of arrays

### astype()

In [706]:
# arr.astype(type)
# - It returns a new array

In [699]:
arr

array([ 45.,   0.,  30.,  40.,   0.,   0.,  70.,  80., 500.])

In [703]:
arr.dtype

dtype('float64')

In [730]:
arr.astype(int)

TypeError: Cannot construct a dtype from an array

In [732]:
arr.astype('int')

array([ 45,   0,  30,  40,   0,   0,  70,  80, 500])

In [736]:
arr=np.array([ 45,   0,  30,  40,   0,   0,  70,  80, 500])
arr

array([ 45,   0,  30,  40,   0,   0,  70,  80, 500])

In [738]:
arr.dtype

dtype('int32')

In [746]:
arr.astype('complex').astype('str').astype('object')

array(['(45+0j)', '0j', '(30+0j)', '(40+0j)', '0j', '0j', '(70+0j)',
       '(80+0j)', '(500+0j)'], dtype=object)

In [748]:
np.__version__

'1.24.3'

In [750]:
arr.astype('complex')

array([ 45.+0.j,   0.+0.j,  30.+0.j,  40.+0.j,   0.+0.j,   0.+0.j,
        70.+0.j,  80.+0.j, 500.+0.j])

In [6]:
arr=np.array([ 45.+0.j,   0.+0.j,  30.+0.j,  40.+0.j,   0.+0.j,   0.+0.j,
        70.+0.j,  80.+0.j, 500.+0.j])

In [754]:
arr

array([ 45.+0.j,   0.+0.j,  30.+0.j,  40.+0.j,   0.+0.j,   0.+0.j,
        70.+0.j,  80.+0.j, 500.+0.j])

In [756]:
arr.dtype

dtype('complex128')

In [1]:
a=5+5j
print(a,type(a))

(5+5j) <class 'complex'>


In [2]:
int(a)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [4]:
import numpy as np

In [8]:
arr

array([ 45.+0.j,   0.+0.j,  30.+0.j,  40.+0.j,   0.+0.j,   0.+0.j,
        70.+0.j,  80.+0.j, 500.+0.j])

In [12]:
arr.astype('int')

C:\Users\ashis\AppData\Local\Temp\ipykernel_17176\3414054417.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  arr.astype('int')


array([ 45,   0,  30,  40,   0,   0,  70,  80, 500])

In [17]:
help(arr.astype)

Help on built-in function astype:

astype(...) method of numpy.ndarray instance
    a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
    
    Copy of the array, cast to a specified type.
    
    Parameters
    ----------
    dtype : str or dtype
        Typecode or data-type to which the array is cast.
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout order of the result.
        'C' means C order, 'F' means Fortran order, 'A'
        means 'F' order if all the arrays are Fortran contiguous,
        'C' order otherwise, and 'K' means as close to the
        order the array elements appear in memory as possible.
        Default is 'K'.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur. Defaults to 'unsafe'
        for backwards compatibility.
    
          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are al

# Condition on arrays

In [21]:
# Conditions on arrays (h_stact, v_stack)
# Iterating over arrays
# Array concatenation
# Sorting of arrays
# Splitting of arrays
# Array broadcasting